/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCorpusRouteImport } from './routes/api.corpus'
import { Route as ApiQuestionsRouteImport } from './routes/api.questions'
import { Route as ApiQuestionsIdRouteImport } from './routes/api.questions.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCorpusRoute = ApiCorpusRouteImport.update({
  id: '/api/corpus',
  path: '/api/corpus',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuestionsRoute = ApiQuestionsRouteImport.update({
  id: '/api/questions',
  path: '/api/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuestionsIdRoute = ApiQuestionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiQuestionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/corpus': typeof ApiCorpusRoute
  '/api/questions': typeof ApiQuestionsRouteWithChildren
  '/api/questions/$id': typeof ApiQuestionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/corpus': typeof ApiCorpusRoute
  '/api/questions': typeof ApiQuestionsRouteWithChildren
  '/api/questions/$id': typeof ApiQuestionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/corpus': typeof ApiCorpusRoute
  '/api/questions': typeof ApiQuestionsRouteWithChildren
  '/api/questions/$id': typeof ApiQuestionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/corpus' | '/api/questions' | '/api/questions/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/corpus' | '/api/questions' | '/api/questions/$id'
  id: '__root__' | '/' | '/api/corpus' | '/api/questions' | '/api/questions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCorpusRoute: typeof ApiCorpusRoute
  ApiQuestionsRoute: typeof ApiQuestionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/corpus': {
      id: '/api/corpus'
      path: '/api/corpus'
      fullPath: '/api/corpus'
      preLoaderRoute: typeof ApiCorpusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/questions': {
      id: '/api/questions'
      path: '/api/questions'
      fullPath: '/api/questions'
      preLoaderRoute: typeof ApiQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/questions/$id': {
      id: '/api/questions/$id'
      path: '/$id'
      fullPath: '/api/questions/$id'
      preLoaderRoute: typeof ApiQuestionsIdRouteImport
      parentRoute: typeof ApiQuestionsRoute
    }
  }
}

interface ApiQuestionsRouteChildren {
  ApiQuestionsIdRoute: typeof ApiQuestionsIdRoute
}

const ApiQuestionsRouteChildren: ApiQuestionsRouteChildren = {
  ApiQuestionsIdRoute: ApiQuestionsIdRoute,
}

const ApiQuestionsRouteWithChildren = ApiQuestionsRoute._addFileChildren(
  ApiQuestionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCorpusRoute: ApiCorpusRoute,
  ApiQuestionsRoute: ApiQuestionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
